packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "hono@<4.12.14": 4.12.14
  "@hono/node-server@<1.19.13": 1.19.13
  "path-to-regexp@>=8 <8.4.0": 8.4.0
  "brace-expansion@<1.1.13": 1.1.13
